version: "3"
services:
  postgresql:
    image: postgres:16
    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
