services:
  mysql:
    image: mysql:8.0-bookworm
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - db-network
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "1.5G"
        reservations:
          cpus: "0.5"
          memory: "512M"

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
