services:
  mysql:
    image: mysql:8.0-bookworm
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - db-network
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "1.5G"
        reservations:
          cpus: "0.5"
          memory: "512M"

  mysql_backup:
    image: mysql:8.0-bookworm
    container_name: mysql-backup
    restart: always
    volumes:
      - ./backups/mysql:/backups
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: >
      sh -c "while true; do
        mysqldump -h mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} > /backups/mysql-$(date +%F).sql;
        find /backups -type f -name '*.sql' -mtime +14 -delete;
        sleep 86400;
      done"
    depends_on:
      - mysql
    networks:
      - db-network

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
