apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-viewer-binding
subjects:
  - kind: Group
    name: redis-viewers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: redis-viewer-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-manager-binding
subjects:
  - kind: User
    name: redis-admin-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: redis-manager-role
  apiGroup: rbac.authorization.k8s.io
