version: "3.8"

services:
  chromadb:
    image: chromadb/chroma:0.6.4.dev419
    container_name: chroma-db
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_DB_DIR=/chroma/.chroma

volumes:
  chroma_data:
